- name: Set up JDK 21
  uses: actions/setup-java@v3
  with:
    distribution: 'temurin'   
    java-version: '21'
    java-package: jdk
    check-latest: false
    server-id: github
    server-username: GITHUB_ACTOR
    server-password: GITHUB_TOKEN
    overwrite-settings: true