name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'   # ← obligatorio
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean verify

      - name: Build Docker image
        run: docker build --file Dockerfile --tag rguzman1217/challenge-tekton-api:ci .
